# Generated by Django 3.2.5 on 2022-07-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massenger_name', models.CharField(blank=True, max_length=255, null=True)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
