# Generated by Django 3.2.5 on 2022-07-05 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eid_Post', '0004_alter_name_action_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='action_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
