# Generated by Django 3.2.5 on 2022-07-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eid_Post', '0006_alter_name_action_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='image',
            field=models.ImageField(null=True, upload_to='files/covers'),
        ),
    ]
